### ISSUE TITLE
ah_ee_repository fails when using include_tags

### ISSUE THREAD

**Issue by bprins** [redhat-cop/ah_configuration#135]
When using `include_tags` with the `ah_ee_repository` module the Automation Hub API returns a HTTP 500 . From the `gunicorn` logging:
```
pulp [None]: django.request:ERROR: Internal Server Error: /api/galaxy/_ui/v1/execution-environments/remotes/
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/lib/python3.9/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/usr/lib/python3.9/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/lib/python3.9/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/usr/lib/python3.9/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/lib/python3.9/site-packages/rest_framework/mixins.py", line 19, in create
    self.perform_create(serializer)
  File "/usr/lib/python3.9/site-packages/rest_framework/mixins.py", line 24, in perform_create
    serializer.save()
  File "/usr/lib/python3.9/site-packages/rest_framework/serializers.py", line 212, in save
    self.instance = self.create(validated_data)
  File "/usr/lib64/python3.9/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/usr/lib/python3.9/site-packages/galaxy_ng/app/api/ui/serializers/execution_environment.py", line 420, in create
    if "*-source" not in validated_data["exclude_tags"]:
TypeError: argument of type 'NoneType' is not iterable
```

I tried to set `exclude_tags` to an empty list but this is not allowed:
```
parameters are mutually exclusive: include_tags|exclude_tags
```

**Comment by djdanielsson** [comment]
can you please provide the Ansible code you were running that produced this error?

**Comment by bprins** [comment]
Forgot to mention it, but I am using the `ee_repository` role included in the repository with the `ah_ee_repositories` key looking something like this:
```
ah_ee_repositories:
  - name: 'ansible-automation-platform-22/ansible-builder-rhel8'
    upstream_name: 'ansible-automation-platform-22/ansible-builder-rhel8'
    registry: 'registry.redhat.io'
    include_tags:
      - '1.1'
```

**Comment by djdanielsson** [comment]
@Tompage1994 have any ideas on this one? I am not seeing anything jump out at me why this isn't working.

**Comment by tonyreveal** [comment]
My customer is getting a similar error without include_tags:

```
---
- name: Include vars
  include_vars: ../vars/ah_ee_repositories.yml

- name: Import ah_configuration role
  import_role:
    name: redhat_cop.ah_configuration.ee_repository
...
```

../vars/ah_ee_repositories.yml:
```
---
ah_ee_repositories:
  - name: 'ansible-automation-platform-22/ee-minimal-rhel8'
    description: 'Testing'
    state: 'present'
    upstream_name: 'ansible-automation-platform-22/ee-minimal-rhel8'
    registry: 'Red Hat Registry'
...
```

Aug 19 10:33:18 cdevpah01a gunicorn[144583]: pulp [None]: django.request:ERROR: Internal Server Error: /api/galaxy/_ui/v1/execution-environments/remotes/
Aug 19 10:33:18 cdevpah01a gunicorn[144583]: Traceback (most recent call last):
Aug 19 10:33:18 cdevpah01a gunicorn[144583]:  File "/usr/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
Aug 19 10:33:18 cdevpah01a gunicorn[144583]:    response = get_response(request)
Aug 19 10:33:18 cdevpah01a gunicorn[144583]:  File "/usr/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
Aug 19 10:33:18 cdevpah01a gunicorn[144583]:    response = wrapped_callback(request, *callback_args, **callback_kwargs)
Aug 19 10:33:18 cdevpah01a gunicorn[144583]:  File "/usr/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
Aug 19 10:33:18 cdevpah01a gunicorn[144583]:    return view_func(*args, **kwargs)
Aug 19 10:33:18 cdevpah01a gunicorn[144583]:  File "/usr/lib/python3.9/site-packages/rest_framework/viewsets.py", line 125, in view
Aug 19 10:33:18 cdevpah01a gunicorn[144583]:    return self.dispatch(request, *args, **kwargs)
Aug 19 10:33:18 cdevpah01a gunicorn[144583]:  File "/usr/lib/python3.9/site-packages/rest_framework/views.py", line 509, in dispatch
Aug 19 10:33:18 cdevpah01a gunicorn[144583]:    response = self.handle_exception(exc)
Aug 19 10:33:18 cdevpah01a gunicorn[144583]:  File "/usr/lib/python3.9/site-packages/rest_framework/views.py", line 469, in handle_exception
Aug 19 10:33:18 cdevpah01a gunicorn[144583]:    self.raise_uncaught_exception(exc)
Aug 19 10:33:18 cdevpah01a gunicorn[144583]:  File "/usr/lib/python3.9/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
Aug 19 10:33:18 cdevpah01a gunicorn[144583]:    raise exc
Aug 19 10:33:18 cdevpah01a gunicorn[144583]:  File "/usr/lib/python3.9/site-packages/rest_framework/views.py", line 506, in dispatch
Aug 19 10:33:18 cdevpah01a gunicorn[144583]:    response = handler(request, *args, **kwargs)
Aug 19 10:33:18 cdevpah01a gunicorn[144583]:  File "/usr/lib/python3.9/site-packages/rest_framework/mixins.py", line 19, in create
Aug 19 10:33:18 cdevpah01a gunicorn[144583]:    self.perform_create(serializer)
Aug 19 10:33:18 cdevpah01a gunicorn[144583]:  File "/usr/lib/python3.9/site-packages/rest_framework/mixins.py", line 24, in perform_create
Aug 19 10:33:18 cdevpah01a gunicorn[144583]:    serializer.save()
Aug 19 10:33:18 cdevpah01a gunicorn[144583]:  File "/usr/lib/python3.9/site-packages/rest_framework/serializers.py", line 212, in save
Aug 19 10:33:18 cdevpah01a gunicorn[144583]:    self.instance = self.create(validated_data)
Aug 19 10:33:18 cdevpah01a gunicorn[144583]:  File "/usr/lib64/python3.9/contextlib.py", line 79, in inner
Aug 19 10:33:18 cdevpah01a gunicorn[144583]:    return func(*args, **kwds)
Aug 19 10:33:18 cdevpah01a gunicorn[144583]:  File "/usr/lib/python3.9/site-packages/galaxy_ng/app/api/ui/serializers/execution_environment.py", line 420, in create
Aug 19 10:33:18 cdevpah01a gunicorn[144583]:    if "*-source" not in validated_data["exclude_tags"]:
Aug 19 10:33:18 cdevpah01a gunicorn[144583]: TypeError: argument of type 'NoneType' is not iterable
Aug 19 10:33:18 cdevpah01a gunicorn[144583]: pulp [-]:  - - [19/Aug/2022:14:33:18 +0000] "POST /api/galaxy/_ui/v1/execution-environments/remotes/ HTTP/1.0" 500 145 "https://pah-dev.cscglobal.com" "Python-urllib/3.9"
Aug 19 10:33:18 cdevpah01a gunicorn[144583]: pulp [-]:  - - [19/Aug/2022:14:33:18 +0000] "POST /api/galaxy/_ui/v1/auth/logout/ HTTP/1.0" 204 0 "https://pah-dev.cscglobal.com" "Python-urllib/3.9"

**Comment by djdanielsson** [comment]
@tonyreveal thanks for the update, what version of hub are they running?

**Comment by tonyreveal** [comment]
@djdanielsson AAP 2.2 / PAH 4.5.
![hub_ver](https://user-images.githubusercontent.com/22101936/185692901-4ade2869-75b4-4dd9-ab20-13d8ae64df81.PNG)
0

**Comment by djdanielsson** [comment]
Thanks, it's good to see that it is 2.2 so this is defiantly a bug of some sort that we will need to track down.

**Comment by sean-m-sullivan** [comment]
With the above PR this is what was tested, it should work, I was unable to replicate your errors, but got new ones of my own. Which I went about fixing.

```
---
- name: Updating Automation remote registeries
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    ah_host: https://hub.node/
    ah_username: admin
    ah_password: secret123
    ah_path_prefix: galaxy
    ah_validate_certs: false
    ah_ee_registries:
      - name: rh-registry
        url: https://registry.redhat.io
        username: redhat_username
        password: password
    ah_ee_repositories:
      - name: 'ansible-automation-platform-22/ansible-builder-rhel8'
        upstream_name: 'ansible-automation-platform-22/ansible-builder-rhel8'
        registry: rh-registry
        include_tags:
          - 1.1.0-57
          - 1.1.0-56
          - 1.1
  collections:
    - redhat_cop.ah_configuration
  roles:
    - redhat_cop.ah_configuration.ee_repository
    - redhat_cop.ah_configuration.ee_repository_sync
...
```
