### ISSUE TITLE
Automation Hub ah_repository fails with error 'Unexpected Field: "parameter": "rate_limit"'

### ISSUE THREAD

**Issue by randy-randerson** [redhat-cop/ah_configuration#136]
We have a monthly Tower job to update our AH repos. Since the last update to role in this collection as noted in this [issue](https://github.com/redhat-cop/ah_configuration/issues/119) where the parameter `rate_limit` was added our job has started failing with the below error:

```
{
    "msg": "Unable to update api/galaxy/content/community/v3/sync/config community, see response",
    "response": {
        "status_code": 400,
        "json": {
            "errors": [
                {
                    "status": "400",
                    "code": "invalid",
                    "title": "Invalid input.",
                    "detail": "Unexpected field",
                    "source": {
                        "parameter": "rate_limit"
                    }
                }
            ]
        }
    },
    "input": {
        "requirements_file": "---\n\ncollections:\n  - name: community.crypto\n  - name: community.general\n  - name: community.postgresql\n  - name: community.vmware\n  - name: community.windows\n  - name: community.aws\n  - name: paloaltonetworks.panos\n  - name: redhat_cop.ah_configuration\n",
        "url": "https://galaxy.ansible.com/api/",
        "tls_validation": true,
        "proxy_url": "<proxy_url>",
        "download_concurrency": "10",
        "rate_limit": "8"
    },
    "invocation": {
        "module_args": {
            "ah_host": "<ah_host>",
            "ah_username": "<user_name>",
            "ah_password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "validate_certs": false,
            "name": "community",
            "url": "https://galaxy.ansible.com/api/",
            "requirements_file": "files/aah_community_requirements.yml",
            "proxy_url": "<proxy_url>,
            "tls_validation": true,
            "download_concurrency": "10",
            "rate_limit": "8",
            "ah_path_prefix": null,
            "ah_token": null,
            "auth_url": null,
            "token": null,
            "username": null,
            "password": null,
            "client_key": null,
            "client_cert": null,
            "ca_cert": null,
            "client_key_path": null,
            "client_cert_path": null,
            "ca_cert_path": null,
            "requirements": null,
            "signed_only": null,
            "proxy_username": null,
            "proxy_password": null
        }
    },
    "_ansible_no_log": false,
    "changed": false,
    "item": {
        "aahRepoName": "community",
        "aahRepoURL": "https://galaxy.ansible.com/api/",
        "aahReqFile": "files/aah_community_requirements.yml"
    },
    "ansible_loop_var": "item",
    "_ansible_item_label": {
        "aahRepoName": "community",
        "aahRepoURL": "https://galaxy.ansible.com/api/",
        "aahReqFile": "files/aah_community_requirements.yml"
    }
}
```

**Comment by randy-randerson** [comment]
Version locking it to `0.8.0` allows it to succeed. 

Here's the playbook we are using:

```
- name: Configure & sync AAH remote repos
  hosts: localhost
  gather_facts: no
  vars_files:                                                                      
    - vars/tower_{{ env }}.yml  
    - vars/tower_secrets.yml
    - inventories/000_cross_env_vars
  tasks:
    - name: Configure the repos
      redhat_cop.ah_configuration.ah_repository:
        ah_host: "{{ aahBase }}"
        ah_username: admin
        ah_password: "{{ aahAdminPass }}"
        validate_certs: false
        name: "{{ item.aahRepoName }}"
        url: "{{ item.aahRepoURL }}"
        requirements_file: "{{ item.aahReqFile }}"
        auth_url: "{{ item.aahRepoAuthURL | default(omit) }}"
        token: "{{ item.aahRepoToken | default(omit) }}"
        proxy_url: "{{ proxy_env.http_proxy }}"
      loop: "{{ aahRepos }}"
```
