### ISSUE TITLE
ah_collection auto approve function broken

### ISSUE THREAD

**Issue by djdanielsson** [redhat-cop/ah_configuration#157]
the ah_collection module has an auto_approve option but currently if set to true it will fail saying something like could not find a collection waiting for approval. I think this has to do with changes to the API/backend that needs to be updated

**Comment by djdanielsson** [comment]
this may be fixed in 0.9.2

**Comment by tonyreveal** [comment]
My current customer is having a problem with auto-approve when publishing collections as a super-user.  But the error received is actually:

"You don't have permission to GET to /api/galaxy/content/inbound-csc/v3/plugin/ansible/imports/collections/ce04e268-9cfb-44b6-8e65-0967657644b4/ (HTTP 403)."

Task and vars files:

```yaml
---
- name: Include vars
  include_vars: ../vars/collections_publish.yml

- name: Import ah_configuration role
  import_role:
    name: redhat_cop.ah_configuration.publish
  vars:
    ah_overwrite_existing: false
    ah_auto_approve: true
    ah_validate_certs: true
...
```

```yaml
---
ah_collections:
  - collection_name: 'csc.infoblox'
    git_url: 'https://github.com/IAD/infoblox_collection.git'
    version: '1.0.3'

  - collection_name: 'csc.active_directory'
    git_url: 'https://github.com/IAD/active_directory_collection.git'
    version: '1.0.3'

...
```
