### ISSUE TITLE
Lookup plugin ah_api is not working

### ISSUE THREAD

**Issue by Alex-Bron** [redhat-cop/ah_configuration#196]
# Summary

When using the ah_api lookup plugin, tasks fail with message:
`unknown doc_fragment(s) in file /home/alex/git/aap/collections/ansible_collections/redhat_cop/ah_configuration/plugins/lookup/ah_api.py: infra.ah_configuration.auth_plugin
`
When manually replacing infra.ah_configuration with redhat_cop.ah_configuration, tasksfail with message:
`An unhandled exception occurred while running the lookup plugin 'redhat_cop.ah_configuration.ah_api'. Error was a <class 'AttributeError'>, original message: 'dict' object has no attribute 'getheaders'. 'dict' object has no attribute 'getheaders'`

# Issue Type

- Bug Report

# Ansible, Collection, Private Automation Hub details

```console (paste below)
ansible --version
ansible [core 2.14.1]
  config file = /home/alex/git/aap/ansible.cfg
  configured module search path = ['/home/alex/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.9/site-packages/ansible
  ansible collection location = /home/alex/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.9.13 (main, Nov  9 2022, 13:16:24) [GCC 8.5.0 20210514 (Red Hat 8.5.0-15)] (/usr/bin/python3.9)
  jinja version = 3.0.3
  libyaml = True

ansible-galaxy collection list
# /usr/share/ansible/collections/ansible_collections
Collection       Version
---------------- -------
redhat.rhel_mgmt 1.1.0  

# /home/alex/.ansible/collections/ansible_collections
Collection              Version
----------------------- -------
ansible.posix           1.4.0  
community.crypto        2.7.1  
community.general       5.8.0  
community.libvirt       1.2.0  
containers.podman       1.9.4  
freeipa.ansible_freeipa 1.8.4  
oasis_roles.system      1.3.0  
redhat.insights         1.0.7  
redhat.rhel_idm         1.8.4

Private Automation Hub version
2.3
```

- ansible installation method: one of source, pip, OS package, EE
OS package and EE

# OS / ENVIRONMENT

Tasks run on localhost (RHEL8) against Private Automation Hub 2.3 on RHEL 8.7

# Desired Behavior

I want to retrieve a list of collections from the rh-certified repository, so I can remove those from the list of requirements.yml entries which then can be configured in the communities repository. The way to retrieve the list of collections is by doing an ah_api lookup for collections on the private automation hub

# Actual Behavior

Snippet of code used for this:

```
- name: Sync the remote collection repositories
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:
    - name: Authenticate and get an API token
      redhat_cop.ah_configuration.ah_token:
        ah_host: "{{ ah_hostname }}"
        ah_username: "{{ ah_username }}"
        ah_password: "{{ ah_password }}"
        validate_certs: "{{ ah_validate_certs | default(true) }}"

    - name: Next, query the Automation Hub for the rh-certified collections
      ansible.builtin.debug:
        msg: "Collections: {{ lookup('redhat_cop.ah_configuration.ah_api', 'collections', host=ah_hostname, oauth_token=ah_token, return_all=true) }}"

    - name: Deauthenticate
      redhat_cop.ah_configuration.ah_token:
        ah_host: "{{ ah_hostname }}"
        ah_token: "{{ ah_token }}"
        validate_certs: "{{ ah_validate_certs | default(true) }}"
        state: absent
```

Task failure messages:
When ah_api is still referring to the infra.ah_configuration collection:

```
TASK [automation_platform : Next, query the Automation Hub for the rh-certified collections] ***
Sunday 08 January 2023  20:56:02 +0000 (0:00:00.052)       0:00:16.143 ******** 
fatal: [localhost]: FAILED! => {"msg": "unknown doc_fragment(s) in file /home/alex/git/aap/collections/ansible_collections/redhat_cop/ah_configuration/plugins/lookup/ah_api.py: infra.ah_configuration.auth_plugin"}
```

When ah_api is modified to refer to redhat_cop.ah_configuration:

```
TASK [automation_platform : Next, query the Automation Hub for the rh-certified collections] ***
Sunday 08 January 2023  20:54:50 +0000 (0:00:00.050)       0:00:16.829 ******** 
fatal: [localhost]: FAILED! => {"msg": "An unhandled exception occurred while running the lookup plugin 'redhat_cop.ah_configuration.ah_api'. Error was a <class 'AttributeError'>, original message: 'dict' object has no attribute 'getheaders'. 'dict' object has no attribute 'getheaders'"}
```

# STEPS TO REPRODUCE

Use the code snippet from above to reproduce.
