### ISSUE TITLE
ah_repository's proxy_* parameters not taken into account

### ISSUE THREAD

**Issue by nodje** [redhat-cop/ah_configuration#263]
I'm using 1.1.1

Maybe I'm missing something obvious as this is super odd, but I can't get it working.

Take for instance:
```
---
ah_repositories: []
ah_repository_certified:
  url: "https://console.redhat.com/api/automation-hub/content/xxxxx-synclist/"
  auth_url: "https://sso.redhat.com/auth/realms/redhat-external/protocol/openid-connect/token"
  proxy_url: "http://myproxy:3131"
  proxy_username: test
  proxy_password: test
  username: usern
  tls_validation: True
  token: !vault | ****
```

All param are processed except `proxy_*`

See the debug log form the ansible-playbook command:
```
changed: [localhost] => {
    "changed": true,
    "id": false,
    "invocation": {
        "module_args": {
            "ah_host": "automationhub.mydomain.com",
            "ah_password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "ah_path_prefix": "galaxy",
            "ah_token": null,
            "ah_username": "admin",
            "auth_url": "https://sso.redhat.com/auth/realms/redhat-external/protocol/openid-connect/token",
            "ca_cert": null,
            "ca_cert_path": null,
            "client_cert": null,
            "client_cert_path": null,
            "client_key": null,
            "client_key_path": null,
            "download_concurrency": "10",
            "name": "rh-certified",
            "password": null,
            "proxy_password": null,
            "proxy_url": null,
            "proxy_username": null,
            "rate_limit": "8",
            "requirements": null,
            "requirements_file": null,
            "signed_only": false,
            "tls_validation": true,
            "token": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "url": "https://console.redhat.com/api/automation-hub/content/xxxxxxxx-synclist/",
            "username": "usern",
            "validate_certs": null
        }
```

I tried to take a peek at the python source code at https://github.com/ansible/ah_configuration/blob/1.1.1/plugins/modules/ah_repository.py#L206

I don't see why proxy_* would be treated differently than for instance "username" which I added as a test.

Hope you can reproduce easily or tell me about something obvious I'm missing
