### ISSUE TITLE
Automation Hub API Token RESET upon repository role usage!

### ISSUE THREAD

**Issue by nodje** [redhat-cop/ah_configuration#275]
Using 1.1.1

I can't understand why this is happening, there must be something somewhere, but I can't identify any issue in either source code or the playbook I use.

Here's the playbook:

group_vars/all/ah_config/ah_main.yml
```
---
ah_configuration_dispatcher_roles:
  - {role: repository, var: ah_repositories, tags: repository}
...
```
group_vars/all/ah_config/ah_repository.yml
```
---
ah_repositories: []
proxy_url: "http://proxy.intra:3131"
ah_repository_certified:
  url: "https://console.redhat.com/api/automation-hub/content/xxxxxxx-synclist/"
  auth_url: "https://sso.redhat.com/auth/realms/redhat-external/protocol/openid-connect/token"
  #proxy_url: "http://proxy.intra:3131"
  tls_validation: True
  token: !vault |
    $ANSIBLE_VAULT;1.1;AES256
    xxxxx

ah_repository_community:
  url: "https://galaxy.ansible.com/api/"
  #proxy_url: "http://proxy.intra:3131"
  tls_validation: True
  requirements:
    - name: redhat_cop.controller_configuration
      version: 2.2.5
    - name: redhat_cop.controller_configuration
      version: 2.3.1
    - name: redhat_cop.ah_configuration
      version: 1.1.1
    - name: community.general
      version: 7.0.1
    - name: community.general
      version: 7.1.0
    - name: community.windows
      version: 1.12.0
    - name: awx.awx
      version: 22.3.0
    - name: community.vmware
      version: 3.4.0
...
```
ahsetup.yml
```
---
- name: Playbook to configure Ansible Automation Hub post installation
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    #ah_hostname: automationhub.staging.intra
    ah_hostname: automationhub.group.intra
    ah_username: admin
    ah_password: !vault |
      $ANSIBLE_VAULT;1.1;AES256
      30643930336231306161343931396539396530646631623966646638643963333832353065333632
      3166386438303265336566336330663933313366363530310a643335653364643462313166333539
      30313266363834633037366639623365356634613562613038396661303961336332386435643832
      3231623761363332610a663431313531656235373837636138366135313130653237346537626533
      6166
  roles:
    - redhat_cop.ah_configuration.dispatch
```

EACH execution of `ansible-playbook ahsetup.yml` makes the existing AH API TOKEN expire.
Or in any case, the usage of the existing `ansible.cfg` or Galaxy Creds with the current token returns a 403.
Our only solution is to load a new one and reconfigure all the existing creds.

This seems crazy I know, but it's really happening.

And not ONLY this, but we have a scheduled JT in AAP2 instances, which simply run the AH repo sync with this playbook (using username/password auth)
```
---
- name: Playbook to sync private Automation Hub
  hosts: localhost
  connection: local
  gather_facts: false

  pre_tasks:
    #- debug: var=automation_hub_hostname

  tasks:
  - name: Sync rh-certified repo and wait up to 3600 seconds
    infra.ah_configuration.ah_repository_sync:
      name: rh-certified
      wait: true
      timeout: 3600
    no_log: true

  - name: Sync community repo and wait up to 3600 seconds
    infra.ah_configuration.ah_repository_sync:
      name: community
      wait: true
      timeout: 3600
    no_log: true
...
```
It works but the API Token also becomes invalid after its execution.

Please Help!!
