### ISSUE TITLE
Collection upload broken 4.7

### ISSUE THREAD

**Issue by sean-m-sullivan** [redhat-cop/ah_configuration#292]
# Summary

Collection upload broken 4.7+ with error:
```
The file (galaxy_ng/dev/standalone-community/galaxy-importer.cfg) was not found"
```

# Issue Type

- Bug Report

# Ansible, Collection, Private Automation Hub details

```console (paste below)

Private Automation Hub version 4.7/master

```

- ansible installation method: one of source, pip, OS package, EE

# OS / ENVIRONMENT

Our internal tests

# Desired Behavior

Upload collection working

# Actual Behavior

Please give some details of what is actually happening.
Include a [minimum complete verifiable example] with:

- playbook / task
- configuration file / list
- error

Play:
```
vars:
    ah_collections:
      - namespace: ansible
        name: automation_hub
        path: "/home/runner/work/{{ git_repo_name }}/{{ git_repo_name }}/ansible-automation_hub-1.0.0.tar.gz"
        wait: true
        interaval: 5
        auto_approve: true
        timeout: 180

    - name: Upload Collection
      ansible.builtin.include_role:
        name: collection
```

```console (error)
failed: [localhost] (item={'failed': 0, 'started': 1, 'finished': 0, 'ansible_job_id': 'j542073910814.8819', 'results_file': '/home/runner/.ansible_async/j542073910814.8819', 'changed': False, '__collection': {'namespace': 'ansible', 'name': 'automation_hub', 'path': '/home/runner/work/galaxy_collection/galaxy_collection/ansible-automation_hub-1.0.0.tar.gz', 'wait': True, 'interaval': 5, 'auto_approve': True, 'timeout': 180}, 'ansible_loop_var': '__collection'}) => {"__collections_job_async_result_item": {"__collection": {"auto_approve": true, "interaval": 5, "name": "automation_hub", "namespace": "ansible", "path": "/home/runner/work/galaxy_collection/galaxy_collection/ansible-automation_hub-1.0.0.tar.gz", "timeout": 180, "wait": true}, "ansible_job_id": "j542073910814.8819", "ansible_loop_var": "__collection", "changed": false, "failed": 0, "finished": 0, "results_file": "/home/runner/.ansible_async/j542073910814.8819", "started": 1}, "ansible_job_id": "j542073910814.8819", "ansible_loop_var": "__collections_job_async_result_item", "attempts": 1, "changed": false, "finished": 1, "msg": "Upload of collection failed: The file (galaxy_ng/dev/standalone-community/galaxy-importer.cfg) was not found", "results_file": "/home/runner/.ansible_async/j542073910814.8819", "started": 1, "stderr": "", "stderr_lines": [], "stdout": "", "stdout_lines": []}
```

# STEPS TO REPRODUCE

Run the tests.

```yaml (playbook/task)

```

```yaml (config/list/array/variables)

```

[minimum complete verifiable example]: http://stackoverflow.com/help/mcve
