### ISSUE TITLE
Token generation with Automation Hub

### ISSUE THREAD

**Issue by otatman** [redhat-cop/ah_configuration#31]
Hello, we are having issues with token generation with Automation Hub. Here are two ways we've tried to publish a collection to AH and the configs we are using. 

Scenario 1 for playbook.yml:
```
---
- name: playbook to push collection from github to private automation hub
  hosts: all
  gather_facts: false
  collections:
    - redhat_cop.ah_configuration
  pre_tasks:
    - name: include vars from ah_configs directory
      include_vars:
        dir: ./var
        extensions: ["yml"]
  tasks:
    - name: publish collections
      include_role: 
        name: publish
      vars:
        ah_auto_approve: true
```
```
Returns the following error:
failed: [tower] (item=/tmp/bwrap_583_swc3ywat/awx_583_b3sqioc9/project/var/tmp/testing_collection/update_collection_test-testing_collection-1.0.0.tar.gz) => {"__ah_collection_file": "/tmp/bwrap_583_swc3ywat/awx_583_b3sqioc9/project/var/tmp/testing_collection/update_collection_test-testing_collection-1.0.0.tar.gz", "ansible_loop_var": "__ah_collection_file", "changed": false, "msg": "Failed to get token: HTTP Error 405: Method Not Allowed", "response": "{\"errors\":[{\"status\":\"405\",\"code\":\"method_not_allowed\",\"title\":\"Method \\\"{method}\\\" not allowed.\",\"detail\":\"Method \\\"GET\\\" not allowed.\"}]}"}
```

Scenrio 2 for playbook.yml:
```
---
- name: playbook to push collection from github to private automation hub
  hosts: all
  gather_facts: false
  collections:
    - redhat_cop.ah_configuration
  pre_tasks:
    - name: include vars from ah_configs directory
      include_vars:
        dir: ./var
        extensions: ["yml"]

  tasks:
    - name: authenticate and get an API token
      ah_token:
        state: present
        ah_host: "{{ ah_host }}"
        ah_username: "{{ ah_username }}"
        ah_password: "{{ ah_password }}"
        ah_path_prefix: "{{ ah_path_prefix }}"
        validate_certs: "{{ ah_validate_certs }}"

    - name: publish collections
      include_role: 
        name: publish
      vars:
        ah_auto_approve: true
```
```
Returns the following error:
fatal: [tower]: FAILED! => {"changed": false, "msg": "The Automation Hub server says you can't make a request with the POST method to this endpoing api/galaxy/v3/auth/token/"}
```

The config files we are using apply to both scenarios.

ah_ansible_config.yml

```
---
automation_hub_list:
  - name: automation_hub
    url: "{{ ah_host }}"
    auth_url: "{{ ah_host }}/api/galaxy/"
    username: "{{ ah_username }}"
    password: "{{ ah_password }}"
 
ansible_config_list:
  settings:
    - header: galaxy
      keypairs: 
        - key: ignore_certs
          value: "(% if validate_certs %)false(% else %)true(% endif %)"
        - key: server_list
          value: "automation_hub"
ah_configuration_working_dir: "var/tmp"

```

ah_auth.yml
```
---
ah_host: "url"
ah_username: "user"
ah_password: "blah"
ah_path_prefix: 'galaxy'
ah_validate_certs: false

```

ah_collections.yml
```
---
ah_collections:
  - collection_name: testing_collection
    git_url: "https://github.com/user/automationhub-collection-test.git"
ah_auto_approve: true

```

ah_ansible_config.yml
```
---
automation_hub_list:
  - name: automation_hub
    url: "{{ ah_host }}"
    auth_url: "{{ ah_host }}/api/galaxy/"
    username: "{{ ah_username }}"
    password: "{{ ah_password }}"
 
ansible_config_list:
  settings:
    - header: galaxy
      keypairs: 
        - key: ignore_certs
          value: "(% if validate_certs %)false(% else %)true(% endif %)"
        - key: server_list
          value: "automation_hub"
ah_configuration_working_dir: "var/tmp"

```
   
ah_namespaces.yml
```
---
ah_namespaces:
  - name: update_collection_test
    email: "user@redhat.com"
    avatar_url: "public"
    description: string
    resources: 
    links:
      - name: "nothing"
        url: "https://github.com/ansible/awx"
    groups:
      - name: system:admins
        object_permissions:
          - "change_namespace"
          - "upload_to_namespace"

```

**Comment by Tompage1994** [comment]
Hi @otatman 

Sorry it's taken a while to get around to this.

I've had a look and it seems the issue seems to be that you are trying to publish a collection to a namespace which does not exist. I can see the error message definitely needs improving so I have raised #32 to fix this.

The fix you'll need to apply here is to first use the `ah_namespace` module to create the namespace defined in your `galaxy.yml` file in the collection. You should then be able to run the `publish` role successfully.

I'm going to close this issue but feel free to re-open it if your issue has not been resolved.

Thanks!

**Comment by otatman** [comment]
Thanks for your response, unfortunately I still get the same 405 error when referencing the namespace role within my playbook. The current state of my playbook and the error message are listed below. 
```
---
- name: playbook to push collection from github to private automation hub
  hosts: all
  gather_facts: false
  collections:
    - redhat_cop.ah_configuration
  pre_tasks:
    - name: include vars from ah_configs directory
      include_vars:
        dir: ./var
        extensions: ["yml"]

  tasks:

    - name: add namespace to AH
      include_role:
        name: namespace
    
    - name: authenticate and get an API token
      ah_token:
        ah_token: "{{ old_ah_token }}"
        state: present
        ah_host: "{{ ah_host }}"
        ah_username: "{{ ah_username }}"
        ah_password: "{{ ah_password }}"
        ah_path_prefix: "{{ ah_path_prefix }}"
        validate_certs: "{{ ah_validate_certs }}"
        
    - name: publish collections
      include_role: 
        name: publish
      vars:
        ah_auto_approve: true
```

```
failed: [tower] (item={'name': 'update_collection_test', 'email': 'jtatman@redhat.com', 'avatar_url': 'public', 'description': 'string', 'resources': None, 'links': [{'name': 'nothing', 'url': 'https://github.com/ansible/awx'}], 'groups': [{'name': 'system:admins', 'object_permissions': ['change_namespace', 'upload_to_namespace']}]}) => {"__namespace_item": {"avatar_url": "public", "description": "string", "email": "jtatman@redhat.com", "groups": [{"name": "system:admins", "object_permissions": ["change_namespace", "upload_to_namespace"]}], "links": [{"name": "nothing", "url": "https://github.com/ansible/awx"}], "name": "update_collection_test", "resources": null}, "ansible_loop_var": "__namespace_item", "changed": false, "msg": "Failed to get token: HTTP Error 405: Method Not Allowed", "response": "{\"errors\":[{\"status\":\"405\",\"code\":\"method_not_allowed\",\"title\":\"Method \\\"{method}\\\" not allowed.\",\"detail\":\"Method \\\"GET\\\" not allowed.\"}]}"}
```

The configuration files I provided initially are the same.

**Comment by otatman** [comment]
Swapping the placement of the namespace and publish role references as such gives a different error

```
---
- name: playbook to push collection from github to private automation hub
  hosts: all
  gather_facts: false
  collections:
    - redhat_cop.ah_configuration
  pre_tasks:
    - name: include vars from ah_configs directory
      include_vars:
        dir: ./var
        extensions: ["yml"]

  tasks:
    
    - name: authenticate and get an API token
      ah_token:
        ah_token: "{{ old_ah_token }}"
        state: present
        ah_host: "{{ ah_host }}"
        ah_username: "{{ ah_username }}"
        ah_password: "{{ ah_password }}"
        ah_path_prefix: "{{ ah_path_prefix }}"
        validate_certs: "{{ ah_validate_certs }}"
        
    - name: publish collections
      include_role: 
        name: publish
      vars:
        ah_auto_approve: true

    - name: add namespace to AH
      include_role:
        name: namespace
  ```

Error statement:
```
fatal: [tower]: FAILED! => {"changed": false, "msg": "The Automation Hub server says you can't make a request with the POST method to this endpoing api/galaxy/v3/auth/token/"}
```
