### ISSUE TITLE
infra.ah_configuration.publish fails to publish more than one collection

### ISSUE THREAD

**Issue by myllynen** [redhat-cop/ah_configuration#327]
With a local automation hub and collection version 2.0.4 using the following with the needed namespace created earlier the publish role fails with a permission denied message:

```
ah_collections:
  - collection_name: myllynen.rhel_ansible_roles
    git_url: https://github.com/myllynen/rhel-ansible-roles
    version: v1.4.11

  - collection_name: myllynen.rhel_image
    git_url: https://github.com/myllynen/rhel-image
    version: v1.1.3
```

```
    msg: You don't have permission to GET
        to /api/galaxy/content/staging/v3/plugin/ansible/imports/collections/<uuid>/
        (HTTP 403).
```

If I run the role with either one commented out then the role works. However, then every second playbook run fails with the "Collection .. exists" error even with ah_auto_approve set to true. In my tests I've restored all the AAP 2.4 VMs from snapshots created after installation so previous runs or leftovers in /var/tmp are not affecting my tests.

Thanks.
