### ISSUE TITLE
collection_repository_sync role has gives 403 for POST request

### ISSUE THREAD

**Issue by kbreit-insight** [redhat-cop/ah_configuration#341]
# Summary

I am using the role `collection_repository_sync` and when I run the playbook this role gives an error that it can't `POST` to `/api/galaxy/pulp/api/v3/repositories/ansible/ansible/1bb7eb41-1385-42dc-afbd-c7df513b8fd7/sync/`.

# Issue Type

- Bug Report

# Ansible, Collection, Private Automation Hub details

```console (paste below)
bash-5.1# ansible --version
ansible [core 2.15.6]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/runner/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.9/site-packages/ansible
  ansible collection location = /home/runner/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.9.18 (main, Sep  7 2023, 00:00:00) [GCC 11.4.1 20230605 (Red Hat 11.4.1-2)] (/usr/bin/python3)
  jinja version = 3.1.2
  libyaml = True
bash-5.1# ansible-galaxy collection list

# /usr/share/ansible/collections/ansible_collections
Collection                     Version
------------------------------ -------
ansible.posix                  1.5.4
ansible.utils                  2.11.0
awx.awx                        23.3.1
community.general              8.0.2
infra.ah_configuration         2.0.4
infra.controller_configuration 2.5.2

Private Automation Hub version
4.6.6
```

- ansible installation method: EE

# OS / ENVIRONMENT

AAP 4.3

# Desired Behavior

Automation Hub should refresh the community remote repository.

# Actual Behavior

Please give some details of what is actually happening.
Include a [minimum complete verifiable example] with:

- playbook / task
- configuration file / list
- error

```console (error)
failed: [conway] (item={'failed': 0, 'started': 1, 'finished': 0, 'ansible_job_id': 'j205325216828.42', 'results_file': '/home/runner/.ansible_async/j205325216828.42', 'changed': False, 'ansible_facts': {'discovered_interpreter_python': '/usr/bin/python3'}, '__collection_repository_sync_item': {'name': 'community'}, 'ansible_loop_var': '__collection_repository_sync_item'}) => {"__collection_repository_sync_job_async_result_item": {"__collection_repository_sync_item": {"name": "community"}, "ansible_facts": {"discovered_interpreter_python": "/usr/bin/python3"}, "ansible_job_id": "j205325216828.42", "ansible_loop_var": "__collection_repository_sync_item", "changed": false, "failed": 0, "finished": 0, "results_file": "/home/runner/.ansible_async/j205325216828.42", "started": 1}, "ansible_job_id": "j205325216828.42", "ansible_loop_var": "__collection_repository_sync_job_async_result_item", "attempts": 3, "changed": false, "finished": 1, "msg": "Start Sync error: You do not have permission to POST /api/galaxy/pulp/api/v3/repositories/ansible/ansible/1bb7eb41-1385-42dc-afbd-c7df513b8fd7/sync/ (HTTP 403).", "results_file": "/home/runner/.ansible_async/j205325216828.42", "started": 1, "stderr": "", "stderr_lines": [], "stdout": "", "stdout_lines": []}
```

# STEPS TO REPRODUCE

```yaml (playbook/task)
  roles:
    - role: infra.ah_configuration.collection_repository_sync
      ah_collection_repositories:
        - name: community
```

```yaml (config/list/array/variables)
  vars:
    ah_host: '{{ hostvars[inventory_hostname]["ah_host"] }}'
```

Note: Credentials are set for the admin user and I'm able to synchronize the repository using the web interface but it fails using the API.

[minimum complete verifiable example]: http://stackoverflow.com/help/mcve

**Comment by sean-m-sullivan** [comment]
can you tell me how you are authenticating, as in the vars you are using. I just tested this and it synced without problem using the follwing

```
---
- name: Test Hub
  hosts: localhost
  connection: local
  become: false
  gather_facts: false
  vars:
    ah_hostname: hubsso.nas
    ah_username: fred
    ah_password: secret123
    ah_path_prefix: galaxy
    ah_validate_certs: false

  roles:
    - role: infra.ah_configuration.collection_repository_sync
      ah_collection_repositories:
        - name: community

```

suspect it is somehow either wrong auth vars, or a permisions problem, but admin should be able to do it.

**Comment by kbreit-insight** [comment]
I'm using environment variables for my credentials. For development I have an `.envrc` file which has the following content:

```
export AH_USERNAME="admin"
export AH_PASSWORD="redacted"
export AH_HOST="hub.example.com"
export AH_VERIFY_SSL="false"
```

For testing purposes I'm also having the playbook read those variables into new variables.

```
    ah_host: '{{ lookup("env", "AH_HOST") }}'
    ah_username: '{{ lookup("env", "AH_USERNAME") }}'
    ah_password: '{{ lookup("env", "AH_PASSWORD") }}'
```

It's still not working. These are ran through execution environments and I am passing the environment variables into the EE.
```
ansible-navigator:
  playbook-artifact:
    enable: False
  execution-environment:
    environment-variables:
      pass:
        - AH_USERNAME
        - AH_PASSWORD
        - AH_HOST
        - AH_VERIFY_SSL
```

If I change the password in `.envrc` so I know it's wrong I get a different error.

```
..."msg": "Authentication error: You do not have permission to GET /api/galaxy/_ui/v1/me/ (HTTP 403)."...
```

**Comment by sean-m-sullivan** [comment]
Please try using the repository_sync role
```
  roles:
    - role: infra.ah_configuration.repository_sync
      ah_collection_repositories:
        - name: community
```

I found out you were using Automation hub 4.6.6, and missed this, The Collection repositories were changed in 4.7, and use a different endpoint. the repostiory/repository_sync role is the one to use with AAP 2.3/Hub 4.6

This should fix the problem.

**Comment by kbreit** [comment]
I've tried this one and ran into different problems so maybe that should be a new issue. But I'm not clear what the right variable name is. Your example is `ah_collection_repositories` but that gives ` ["ah_collection_repositories. Supported parameters include:...`. The documentation says `ah_repositories` which gives ```["ah_repositories. Supported parameters include:...` and the example has `ah_repository_certified` and `ah_repository_community` with the contents reflecting a regular configuration update and not sync.

Here's my current role stanza.

```
  roles:
    - role: infra.ah_configuration.repository_sync
      ah_repositories:
        - name: community
```

**Comment by sean-m-sullivan** [comment]
You are right, and the documentation is off, and we need to update that. what was the error you got with the new instantiation.

**Comment by sean-m-sullivan** [comment]
Found the issue in the argument spec, it should have shown up in testing but it looks to be overlooked, this will fix it
```
---
argument_specs:
  main:
    short_description: An Ansible Role to sync repositories in Automation Hub.
    options:
      ah_repositories:
        default: []
        required: false
        description: Data structure describing the collection repositories to sync.
        type: list
        elements: dict
 ```
 
 in repository_sync/meta/argument_specs, same in repository role. Will work on getting a fix out.
