### ISSUE TITLE
ah_collection fails to delete collection when version not specified

### ISSUE THREAD

**Issue by kk-at-redhat** [redhat-cop/ah_configuration#355]
# Summary

ah_collection is not able to delete collection when version is not specified. Should be working according to the documentation:
If absent without version, will delete the collection and all versions. 

# Issue Type

- Bug Report

# Ansible, Collection, Private Automation Hub details

```
ansible --version
ansible [core 2.14.2]
  config file = None
  configured module search path = ['/home/kk/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.9/site-packages/ansible
  ansible collection location = /home/kk/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.9.14 (main, Nov  7 2022, 00:00:00) [GCC 11.3.1 20220421 (Red Hat 11.3.1-2)] (/usr/bin/python3)
  jinja version = 3.1.2
  libyaml = True

ansible-galaxy collection list
Collection             Version
---------------------- -------
ansible.controller     4.4.7
awx.awx                23.2.0
infra.ah_configuration 2.0.4

Private Automation Hub version
Server version 4.6.3
Pulp Ansible Version 0.15.0
UI Version 4.6.3
```

Ansible installation method: OS package

# OS / ENVIRONMENT

Red Hat Enterprise Linux release 9.1 (Plow)

# Desired Behavior

Delete all versions of the collection

# Actual Behavior

Error message: AttributeError: 'NoneType' object has no attribute 'split'

```
File \"/usr/lib64/python3.9/runpy.py\", line 225, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/lib64/python3.9/runpy.py\", line 97, in _run_module_code\n    _run_code(code, mod_globals, init_globals,\n  File \"/usr/lib64/python3.9/runpy.py\", line 87, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_infra.ah_configuration.ah_collection_payload_c4xyv_4f/ansible_infra.ah_configuration.ah_collection_payload.zip/ansible_collections/infra/ah_configuration/plugins/modules/ah_collection.py\", line 227, in <module>\n  File \"/tmp/ansible_infra.ah_configuration.ah_collection_payload_c4xyv_4f/ansible_infra.ah_configuration.ah_collection_payload.zip/ansible_collections/infra/ah_configuration/plugins/modules/ah_collection.py\", line 146, in main\nAttributeError: 'NoneType' object has no attribute 'split'\n"
```

# STEPS TO REPRODUCE
Try to delete collections with the following tasks:
```
- name: Get list of published collections
  ansible.builtin.set_fact:
    published_collections: "{{ query('infra.ah_configuration.ah_api', 'collections') }}"

- name: Delete published collections
  infra.ah_configuration.ah_collection:
    name: "{{ item.name }}"
    namespace: "{{ item.namespace }}"
    state: absent
  loop: "{{ published_collections[0] }}"
```
