### ISSUE TITLE
infra.ah_configuration.publish leaves clone dirs behind

### ISSUE THREAD

**Issue by myllynen** [redhat-cop/ah_configuration#377]
With a local automation hub and collection version 2.0.6 using the following with the needed namespace created earlier the publish role works fine but leaves the collection clone/build directory in /var/tmp:

```
ah_collections:
  - collection_name: myllynen.rhel_ansible_roles
    git_url: https://github.com/myllynen/rhel-ansible-roles
    version: v1.7.4
```

It would be nice the remove the clone/build directory after publishing a collection. Thanks.
