### ISSUE TITLE
ah_collection_upload fails uploading via a https path (filename renamed)

### ISSUE THREAD

**Issue by amunro-tsl** [redhat-cop/ah_configuration#400]
# Summary

When using a https path from ansible-galaxy, upload fails with this error:
```
TASK [Upload collection community-crypto-2.16.2 from galaxy] *******************
fatal: [automation_hub]: FAILED! => {"changed": false, "msg": "Unable to create collections from /root/.ansible/tmp/ansible-tmp-1717058702.5580997-800-101049108611006/community-crypto-2.16.2x866_e8g.tar.gz: Invalid filename community-crypto-2.16.2x866_e8g.tar.gz. Expected format: namespace-name-version.tar.gz"}
```

# Issue Type

- Bug Report

# Ansible, Collection, Private Automation Hub details

collection version: infra.ah_configuration:2.0.6

```console (paste below)
$ ansible --version
ansible [core 2.16.7]
  config file = /home/amunro/.ansible.cfg
  configured module search path = ['/home/amunro/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/amunro/.local/lib/python3.11/site-packages/ansible
  ansible collection location = /home/amunro/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/amunro/.local/bin/ansible
  python version = 3.11.4 (main, Jun  6 2023, 22:16:46) [GCC 11.3.0] (/home/linuxbrew/.linuxbrew/opt/python@3.11/bin/python3.11)
  jinja version = 3.1.4
  libyaml = True

$ cat collections/requirements.yml 
---
collections:
  - name: infra.controller_configuration
    version: 2.7.1
  - name: ansible.controller
    version: 4.5.6
  - name: amazon.aws
    version: 7.5.0
  - name: infra.ah_configuration
    version: 2.0.6

$ cat .gitlab-ci/python-requirements.txt 
ansible==8.7.0
ansible-lint==6.22.2
ansible-compat==4.1.11
boto3==1.34.*
botocore==1.34.*
yamllint==1.32.0
```
collection version: infra.ah_configuration:2.0.6 (latest)
Private Automation Hub version: Installed from aap v2.4-6.2 (25/4/2024) bundle.

- ansible installation method: one of source, pip, OS package, EE

# OS / ENVIRONMENT

Docker image built from docker:24.0.6-dind.

# Desired Behavior

# Actual Behavior

File got renamed when downloaded and then when uploaded had a different name.
Docs: https://galaxy.ansible.com/ui/repo/published/infra/ah_configuration/content/module/ah_collection_upload/

Please give some details of what is actually happening.
Include a [minimum complete verifiable example] with:

- playbook / task
- configuration file / list
- error

```console (error)

```

# STEPS TO REPRODUCE

Ansible code for this (Tom Page originally created this for us):

```yaml (playbook/task)
$ cat ah_automator.yml 
---
- name: Add objects to Private Automation hub
  hosts: automation_hub
  connection: local
  vars:
    ah_hostname: "{{ lookup('ansible.builtin.env', 'AH_HOST') }}"
  roles:
    - infra.ah_configuration.dispatch

  post_tasks:
      - name: Upload collection community-crypto-2.16.2 from galaxy
      infra.ah_configuration.ah_collection_upload:
        ah_password: '{{ ah_password }}'
        path: https://galaxy.ansible.com/download/community-crypto-2.16.2.tar.gz

```
How to run:
```yaml (config/list/array/variables)
$ ansible-playbook ah_automator.yml -i base_config -e "ah_password={{ lookup('amazon.aws.secretsmanager_secret', '${AH_PASSWORD_ARN}') }}"
```

**Comment by Tompage1994** [comment]
I have raised a fix. For now, a workaround would be to use the URI module
```
- name: Download collection community-crypto-2.16.2 from galaxy
  ansible.builtin.uri:
    url: https://galaxy.ansible.com/download/community-crypto-2.16.2.tar.gz
    dest: .
  register: galaxy_download

- name: Upload collection community-crypto-2.16.2
  infra.ah_configuration.ah_collection_upload:
    ah_password: '{{ ah_password }}'
    path: "{{ galaxy_download.dest }}"
```

**Comment by amunro-tsl** [comment]
Thanks @Tompage1994 .

**Comment by amunro-tsl** [comment]
This worked for me:
```
    - name: Download collection community-crypto-2.16.1 from galaxy
      ansible.builtin.uri:
        url: https://galaxy.ansible.com/download/community-crypto-2.16.1.tar.gz
        dest: .
      register: galaxy_download_0

    - name: Upload collection community-crypto-2.16.1
      infra.ah_configuration.ah_collection_upload:
        ah_username: admin
        ah_password: '{{ ah_password }}'
        path: "{{ galaxy_download_0.path }}"
```
