### ISSUE TITLE
Add new_name option for ah_ee_* modules

### ISSUE THREAD

**Issue by Tompage1994** [redhat-cop/ah_configuration#44]
Similar to exists for `ah_namespace`

**Comment by herve4m** [comment]
Let me think about it and do some research.

First thoughts:

Renaming objects with the Pulp container API is not easy. Namespaces cannot be renamed.
For repositories, I might add a `new_name` variable but I will only allow the repository part (```srv.example.com/<namespace>/<repo>:<tag>```) to be renamed.
However, image names without a namespace (`srv.example.com/http-minimum:latest` for example) cannot be renamed (I'll do more research)

```
----
# SUCCESS: the new name does not include the namespace part.
# The resulting name for the repository is ansible-automation-platform-20-early-access/supported

- name: Ensure the repository has the new name
  redhat_cop.ah_configuration.ah_ee_repository:
    name: ansible-automation-platform-20-early-access/ee-supported-rhel8
    new_name: supported


# FAIL: the new name includes a new namespace part. The module reports the error

- name: Ensure the repository has the new name
  redhat_cop.ah_configuration.ah_ee_repository:
    name: ansible-automation-platform-20-early-access/ee-supported-rhel8
    new_name: aap20/supported


# SUCCESS: the new name includes the namespace part, but that part does not change.
# The resulting name for the repository is ansible-automation-platform-20-early-access/supported

- name: Ensure the repository has the new name
  redhat_cop.ah_configuration.ah_ee_repository:
    name: ansible-automation-platform-20-early-access/ee-supported-rhel8
    new_name: ansible-automation-platform-20-early-access/supported


# FAIL: cannot rename images without a namespace part. The module reports the error

- name: Ensure the repository has the new name
  redhat_cop.ah_configuration.ah_ee_repository:
    name: httpd-minimal
    new_name: web-min
```

Pulp container terminology:

```
hub.lab.example.com/ansible-automation-platform-20-early-access/ee-minimal-rhel8:latest
                    \_________________________________________/                  \____/
                                     Namespace                                     Tag
                    \_________________________________________________________/
                                                Repository

Namespace name: ansible-automation-platform-20-early-access
Repository name: ansible-automation-platform-20-early-access/ee-minimal-rhel8
Tag: latest
```

Pulp namespace objects manage access rights to the container images they contain.
There is no API  to rename namespaces (https://docs.pulpproject.org/pulp_container/restapi.html).

Pulp repository objects can be renamed, including the namespace part. However, if that namespace part changes, Pulp creates a new namespace object. All the access rights that the user might have set to the old namespace are not copied over, and the old namespace still exists.

Images have no name (they have a SHA256 digest) so they cannot be renamed :)
