### ISSUE TITLE
Confusing vars `ah_host` vs `ah_hostname`.

### ISSUE THREAD

**Issue by ctodea** [redhat-cop/ah_configuration#65]
For using the collection I've defined `ah_hostname` as defined in the defaults, for instance (`roles/user/defaults/main.yml`) [states](https://github.com/redhat-cop/ah_configuration/blob/devel/roles/user/defaults/main.yml#L5):

`# ah_hostname: "{{ inventory_hostname }}"`

So I've defined my playbook as
```
- name: Playbook to configure automation hub after installing it
  hosts: all

  vars:
    ah_validate_certs: false
    ah_hostname: ah00
    galaxy_server: # omitted 
    ah_oauthtoken: !vault |
      # omitted
  collections:
    - redhat_cop.ah_configuration
  roles:
  [ omitted ]
```

Which fails complaining about the `ah_host` not being defined.
The README [does mention](https://github.com/redhat-cop/ah_configuration/blob/devel/roles/user/README.md?plain=1#L8) `ah_host` is needed, so maybe its just the `defaults/main.yml` that needs an update.

That said, in the [controller_configuration](https://github.com/redhat-cop/controller_configuration) the var is called `controller_hostname`. So for the sake of consistency perhaps is a better idea to change `ah_host` to `ah_hostname`.
